image:
  - Visual Studio 2022

version: 0.1.1-{build}

skip_tags: false

platform:
  - x64
  - x86
configuration: Release

clone_folder: C:\totalcmd-hrx

install:
  - set PATH=C:\msys64\mingw64\bin;C:\msys64\mingw32\bin;C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  -
  - if "%Platform:x=%"=="64" (set BITNESS=64) else (set BITNESS=32)
  - if "%BITNESS%"=="64" (set WCX=wcx64) else (set WCX=wcx)
  - if "%BITNESS%"=="64" (set ARCH=x86_64) else (set ARCH=i686)
  -
  - bash -lc "pacman --needed --noconfirm -Sy pacman-mirrors"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -Syyu"
  - bash -lc "pacman --noconfirm -S mingw-w64-$ARCH-toolchain zip"
  -
  - curl -SL https://win.rustup.rs/ -oC:\rustup-init.exe
  - C:\rustup-init.exe -y --default-host="%ARCH%-pc-windows-gnu"

build: off
build_script:
  - git submodule update --init --recursive
  - cargo build --verbose --release
  -
  - mkdir totalcmd-hrx-v0.1.1-%BITNESS%bit
  - cp target\release\totalcmd_hrx.dll totalcmd-hrx-v0.1.1-%BITNESS%bit\totalcmd-hrx.%WCX%
  - strip --strip-all --remove-section=.comment --remove-section=.note totalcmd-hrx-v0.1.1-%BITNESS%bit\totalcmd-hrx.%WCX%
  - sed -e "s/#VERSION#/v0.1.1/g" -e "s/#BITNESS#/%BITNESS%/g" -e "s/#WCX#/%WCX%/g" pluginst.inf > totalcmd-hrx-v0.1.1-%BITNESS%bit\pluginst.inf
  - cp LICENSE README.md totalcmd-hrx-v0.1.1-%BITNESS%bit
  - zip -r9j totalcmd-hrx-v0.1.1-%BITNESS%bit.zip totalcmd-hrx-v0.1.1-%BITNESS%bit

test: off

artifacts:
  - path: totalcmd-hrx-v0.1.1-%BITNESS%bit.zip

deploy:
  provider: GitHub
  artifact: totalcmd-hrx-v0.1.1-%BITNESS%bit.zip
  auth_token:
    secure: F9auuxFPHvnELZYfPe7+uRR7ymEXMGin8lJeGdfLcZ+hXZrx2KyAXWxLC/dvrpZSNDy434qclCIAuWxW6HjiKA5KlgMrCpgX0bsOxLYKUdpBmXjuX5GkjcH/H6NnPBD4
  on:
    appveyor_repo_tag: true

notifications:
  - provider: Email
    to: nabijaczleweli@gmail.com
    on_build_status_changed: true
